language: java
sudo: required
dist: bionic

jdk:
  - openjdk10

addons:
  apt:
    packages:
      - ant
  sonarcloud:
    organization: "dita-ot-plugins"
    token:
      secure: "JXtwYh+LQxDUKWKK98JM6AKGJqlEtwLbdiHNQ/efS26MjV+m/5iSVYB847TjbeNwPNQbTknuZLvEaKShaQH7Ks0dlT2KwWFJd1tLZ5IAWxM8lt0/R7EJNP/fuKKWmrwdzt+chIzu9QQykjWbwojwrhpxrhvPcVYtT6rTYAjHI6eRDUxqX17NtlhdISaXd4rhG3nDs1Ao0sUFzwEFrA6BgvVzxMxC0jHPAZgGPkL1l7zcQf+l8hJb+aKXHGhiFWYygzcOJQZsN74L0Rf8vqrGY7hf7SBZVu/zzQFMy2Ulp/+KHl5r3xmrecWYH7gM5eheiKY9loMMxUkUy429kl/MSra+1ZZxvsg/FvFr/iRzlx7GRzQ0YzhU8vJlgXNofJIkh3hScZenZjQVLorkHuvsKLbHVY9R2WaWH5lKPBqWCFfVOAqVgrsaBMDIQ45iYkfR0enXVdplwPGsrKYr1XcMdhjq/oOxfypwMdiY97g2V+v8i91DRqmxd5TL4RlNo2vykD9HNb+P5BHqoXYPH57eXXavOm8kDFZFnVEdYjijwy58aEUs23uwDuFJO6xb24gdGzcAFo/pRBwGnm7VJYS0afmBpybT4Zfwp+4lQLgwviGhBiIzhcQFi1pGb9FbxI5NGhVMH62AOLPEYwC2C/qhqpw+E6PFI5kdrHvn1lUxjg4="

before_install:
  - zip -r com.here.validate.svrl.overrides.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita

install:
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/doctales/org.doctales.xmltask/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/com.here.validate.svrl/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install com.here.validate.svrl.overrides.zip 

script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/com.here.validate.svrl.overrides -f unit-test --output . -v

jobs:
  include:
    - stage: test
      name: "Unit Tests: DITA_OT=3.3"
      env: DITA_OT=3.4

      before_script:
        - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/com.here.validate.svrl.overrides -f xsl-instrument

      after_success:
        - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
        - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report
        - rm -rf dita-ot-$DITA_OT
        - sonar-scanner 
